-- MySQL Script generated by MySQL Workbench
-- dim. 02 déc. 2018 22:39:10 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema allsponsored
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema allsponsored
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `allsponsored` DEFAULT CHARACTER SET utf8 ;
USE `allsponsored` ;

-- -----------------------------------------------------
-- Table `allsponsored`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`user` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(80) NULL,
  `first_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `allsponsored`.`user` (`last_name`, `first_name`, `email`, `status`, `role`, `password`) VALUES ('Lucereau', 'Steven', 'stevens.lucereau@allsponsored.com ', 'active', 'admin', '12345');

-- -----------------------------------------------------
-- Table `allsponsored`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`project` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(300) NULL,
  `status` VARCHAR(45) NULL,
  `visual_shirt` VARCHAR(300) NULL,
  `url_summary` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_project_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `allsponsored`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_project_user_idx` ON `allsponsored`.`project` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`club` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`club` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(300) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(200) NULL,
  `name` VARCHAR(100) NULL,
  `phone` INT NULL,
  `url_logo` LONGTEXT NULL,
  `url_logo_vectorized` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `allsponsored`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`contract` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `club_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `url_contract` LONGTEXT NULL,
  `url_signed_contract` LONGTEXT NULL,
  `status` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `project_id`, `club_id`),
  CONSTRAINT `fk_contract_project2`
    FOREIGN KEY (`project_id`)
    REFERENCES `allsponsored`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_club1`
    FOREIGN KEY (`club_id`)
    REFERENCES `allsponsored`.`club` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contract_project2_idx` ON `allsponsored`.`contract` (`project_id` ASC);

CREATE INDEX `fk_contract_club1_idx` ON `allsponsored`.`contract` (`club_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`order` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `delivery_address` VARCHAR(400) NULL,
  `reference` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `tracking_number` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`id`, `contract_id`),
  CONSTRAINT `fk_order_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `allsponsored`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_contract1_idx` ON `allsponsored`.`order` (`contract_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`product` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `category` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `allsponsored`.`order_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`order_has_product` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`order_has_product` (
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `quantity` INT NULL,
  `size` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  CONSTRAINT `fk_product_has_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `allsponsored`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `allsponsored`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_has_order_order1_idx` ON `allsponsored`.`order_has_product` (`order_id` ASC);

CREATE INDEX `fk_product_has_order_product1_idx` ON `allsponsored`.`order_has_product` (`product_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`survey` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`survey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`id`, `contract_id`),
  CONSTRAINT `fk_survey_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `allsponsored`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_survey_contract1_idx` ON `allsponsored`.`survey` (`contract_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`sponsor` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`sponsor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `allsponsored`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`question` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `allsponsored`.`survey_has_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`survey_has_question` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`survey_has_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `survey_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer` INT NULL,
  `comment` LONGTEXT NULL,
  PRIMARY KEY (`id`, `survey_id`, `question_id`),
  CONSTRAINT `fk_survey_has_question_survey1`
    FOREIGN KEY (`survey_id`)
    REFERENCES `allsponsored`.`survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_has_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `allsponsored`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_survey_has_question_survey1_idx` ON `allsponsored`.`survey_has_question` (`survey_id` ASC);

CREATE INDEX `fk_survey_has_question_question1_idx` ON `allsponsored`.`survey_has_question` (`question_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`project_has_sponsor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`project_has_sponsor` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`project_has_sponsor` (
  `project_id` INT NOT NULL,
  `sponsor_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `sponsor_id`),
  CONSTRAINT `fk_project_has_sponsor_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `allsponsored`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_sponsor_sponsor1`
    FOREIGN KEY (`sponsor_id`)
    REFERENCES `allsponsored`.`sponsor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_project_has_sponsor_sponsor1_idx` ON `allsponsored`.`project_has_sponsor` (`sponsor_id` ASC);

CREATE INDEX `fk_project_has_sponsor_project1_idx` ON `allsponsored`.`project_has_sponsor` (`project_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`action` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL,
  `url_image` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`id`, `contract_id`),
  CONSTRAINT `fk_action_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `allsponsored`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_action_contract1_idx` ON `allsponsored`.`action` (`contract_id` ASC);


-- -----------------------------------------------------
-- Table `allsponsored`.`contract_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `allsponsored`.`contract_has_product` ;

CREATE TABLE IF NOT EXISTS `allsponsored`.`contract_has_product` (
  `contract_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`contract_id`, `product_id`),
  CONSTRAINT `fk_contract_has_product_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `allsponsored`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `allsponsored`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_contract_has_product_product1_idx` ON `allsponsored`.`contract_has_product` (`product_id` ASC);

CREATE INDEX `fk_contract_has_product_contract1_idx` ON `allsponsored`.`contract_has_product` (`contract_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
